config/routes.rb
Rails.application.routes.draw do

  #omniauth_callbacksコントローラーを定義することで、各SNSからの認証リクエストに対するコールバック関数を受け取れる(Rails routesで確認可)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    #サインアウトを別箇で用意しないとログアウト処理ができない為記述
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #トップページ
  root to: 'homes#index'

  #カテゴリ一覧用のルーティング記述(現時点では不使用)
  resources :brands_category, only: [:index, :show] 
  resources :category, only: [:index, :show] 

  #新規登録関連のルーティング記述
  resources :signup do
    collection do
      get "session_clear"
      get 'personal'
      get 'sms'
      get 'residence'
      get "done"
    end
  end
  post "signup/create" => "signup#create" #URIを取得する為作成
  
  #クレジット登録関連のルーティング記述
  resources :credit_card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_card#pay'
      post 'destroy', to: 'credit_card#destroy'
    end
  end


  #itemのshowアクションで商品詳細
  resources :items do
    collection do
      get 'search' => 'items#search' #検索
      delete :imgdestroy, path: '/image/:id' #編集での画像削除用アクション
    end
  end

  #マイページ
  resources :mypages, only: [:show] do
    collection do
      # get 'edit', to: 'mypages#edit'#プロフィール編集用      意味不明につき残すだけ残します
      # patch 'edit', to: 'mypages#update'#プロフィール更新用      
      get 'credit' # カード情報登録
      get 'logout' #ログアウト用ページ
      get 'identification' #本人情報
      get 'profile' #プロフィール情報
    end
    member do
      get 'list'#出品リスト
    end
  end  

  #購入
  resources :transaction, only: [:index, :show] do
    collection do 
      get 'done', to: 'transaction#done'#購入完了
    end
    member do
      post 'pay', to: 'transaction#pay'#購入、支払い
      patch 'pay', to: 'transaction#pay' #更新
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  # validates :zip_code, :prefecture, :city, :number, :user_id, presence: :true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brands_category.rb
class BrandsCategory < ApplicationRecord
  has_many :items
end

app/models/category.rb
class Category < ApplicationRecord
  # 現時点では使用していないためコメントアウト化
  # has_ancestry
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :brands_category
  belongs_to :size, optional: true
  belongs_to :item_condition
  
end

app/models/item_condition.rb
class ItemCondition < ApplicationRecord
  has_many :items
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  enum prefecture_area:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :item, optional: true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :credit_cards, dependent: :destroy

  validates :nickname, :email, :encrypted_password, :family_name, :first_name, :family_name_kana, :first_name_kana, :year, :month, :day, presence: :true
  validates :family_name_kana, :first_name_kana, presence: :true, if: :name_kana?

  #各SNSより取得したprovider情報をauthに代入し、Userテーブル内に該当するレコードがあればuserに代入
    def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    #userがなければ新規インスタンスをハッシュ形式で作成
    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        nickname: auth.info.name,
      )
    end
    #userを本メソッドの返り値とする
    user
  end

  #カナカナ入力のバリデーション
  def name_kana?
    input_type = /^([ァ-ン]|ー)+$/
  end

end

app/controllers/credit_card_controller.rb
class CreditCardController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:new, :destroy, :show]

  def new
    if @card
      redirect_to credit_card_path(current_user.id)
    end
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to done_signup_index_path
      else
        redirect_to action: "pay"
      end
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def destroy #PayjpとCardデータベースを削除します
    if @card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
    #下記削除が完了した後のページ遷移先を変更予定 未実装（移動ページがない）
      redirect_to action: "new"
  end

  

  private

  def set_card
    @card = CreditCard.where(user_id: current_user.id).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_card_helper.rb
module CreditCardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credit_card/new.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg", alt: "mercari"
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status

  .single-main
    .l-single-container
      .l-chapter-container
        %h2.l-chapter-head  クレジットカード情報の入力
        = form_tag(pay_credit_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class:"l-single-inner registration-form") do
          .l-single-content
            .form-group
              %label カード番号
              %span.form-require 必須
              = text_field_tag "number", "", class: "input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %br
              %ul.signup-card-list
                %li
                  = image_tag "", alt: "", height: "20", width: "49"
                %li
                  = image_tag "", alt: "", height: "20", width: "34"
                %li
                  = image_tag "", alt: "", height: "20", width: "30"
                %li
                  = image_tag "", alt: "", height: "20", width: "32"
                %li
                  = image_tag "", alt: "", height: "20", width: "21"
                %li
                  = image_tag "", alt: "", height: "20", width: "32"
                %li
                  = image_tag "", alt: "", height: "20", width: "32"
            .form-group.signup-form-expire
              %label 有効期限
              %span.form-require 必須
              %br/
              .select-wrap.half
                %select#exp_month.select-default{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %i.icon-arrow-bottom
                %span 月
              .select-wrap.half
                %select#exp_year.select-default{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %i.icon-arrow-bottom
                %span 年
              %ul#expire-mm-error-wrapper.has-error-text
              %ul#expire-yy-error-wrapper.has-error-text
            .form-group
              %label セキュリティコード
              %span.form-require 必須
              = text_field_tag "cvc", "", class: "input-default", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              #card_token
              = submit_tag "追加する", id:"token_submit", class:"btn-default btn-red"
  
= render "footer"

app/views/credit_card/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(credit_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する


  