config/routes.rb
Rails.application.routes.draw do

  #omniauth_callbacksコントローラーを定義することで、各SNSからの認証リクエストに対するコールバック関数を受け取れる(Rails routesで確認可)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    #サインアウトを別箇で用意しないとログアウト処理ができない為記述
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #トップページ
  root to: 'homes#index'

  #カテゴリ一覧用のルーティング記述(現時点では不使用)
  resources :brands_category, only: [:index, :show] 
  resources :category, only: [:index, :show] 

  #新規登録関連のルーティング記述
  resources :signup do
    collection do
      get "session_clear"
      get 'personal'
      get 'sms'
      get 'residence'
      get "done"
    end
  end
  post "signup/create" => "signup#create" #URIを取得する為作成
  
  #クレジット登録関連のルーティング記述
  resources :credit_card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_card#pay'
      post 'destroy', to: 'credit_card#destroy'
    end
  end


  #itemのshowアクションで商品詳細
  resources :items do
    collection do
      get 'search' => 'items#search' #検索
      delete :imgdestroy, path: '/image/:id' #編集での画像削除用アクション
    end
  end

  #マイページ
  resources :mypages, only: [:show] do
    collection do
      # get 'edit', to: 'mypages#edit'#プロフィール編集用      意味不明につき残すだけ残します
      # patch 'edit', to: 'mypages#update'#プロフィール更新用      
      get 'credit' # カード情報登録
      get 'logout' #ログアウト用ページ
      get 'identification' #本人情報
      get 'profile' #プロフィール情報
    end
    member do
      get 'list'#出品リスト
    end
  end  

  #購入
  resources :transaction, only: [:index, :show] do
    collection do 
      get 'done', to: 'transaction#done'#購入完了
    end
    member do
      post 'pay', to: 'transaction#pay'#購入、支払い
      patch 'pay', to: 'transaction#pay' #更新
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  # validates :zip_code, :prefecture, :city, :number, :user_id, presence: :true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brands_category.rb
class BrandsCategory < ApplicationRecord
  has_many :items
end

app/models/category.rb
class Category < ApplicationRecord
  # 現時点では使用していないためコメントアウト化
  # has_ancestry
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :brands_category
  belongs_to :size, optional: true
  belongs_to :item_condition
  
end

app/models/item_condition.rb
class ItemCondition < ApplicationRecord
  has_many :items
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  enum prefecture_area:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :item, optional: true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :credit_cards, dependent: :destroy

  validates :nickname, :email, :encrypted_password, :family_name, :first_name, :family_name_kana, :first_name_kana, :year, :month, :day, presence: :true
  validates :family_name_kana, :first_name_kana, presence: :true, if: :name_kana?

  #各SNSより取得したprovider情報をauthに代入し、Userテーブル内に該当するレコードがあればuserに代入
    def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    #userがなければ新規インスタンスをハッシュ形式で作成
    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        nickname: auth.info.name,
      )
    end
    #userを本メソッドの返り値とする
    user
  end

  #カナカナ入力のバリデーション
  def name_kana?
    input_type = /^([ァ-ン]|ー)+$/
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  protect_from_forgery except: :personal


  def session_clear
    #　メールアドレスで登録するをクリックしたらsessionを全削除する(uidやprovider情報も消す為)
    reset_session
    redirect_to personal_signup_index_path
  end

  def personal
    @user = User.new 
  end

  def sms
    #user.newのformデータをsessionに格納
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:family_name] = user_params[:family_name]
    session[:first_name] = user_params[:first_name]
    session[:family_name_kana] = user_params[:family_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:year] = user_params[:year]
    session[:month] = user_params[:month]
    session[:day] = user_params[:day]
    if session[:uid] == nil
      session[:password] = user_params[:password]
      session[:password_confirmation] = user_params[:password]
    end
    @address = Address.new 
  end

  def residence
    session[:phone_number] = address_params[:phone_number]
    @address = Address.new
  end

  def create
    @user = User.new(
      nickname: session[:nickname], 
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      family_name: session[:family_name], 
      first_name: session[:first_name], 
      family_name_kana: session[:family_name_kana], 
      first_name_kana: session[:first_name_kana],
      year: session[:year],
      month: session[:month],
      day: session[:day],
      provider: session[:provider],
      uid: session[:uid]
    )
    if @user.save!
      #trueの場合下記ifの実行
      #falseの場合personalにredirect
      session[:zip_code] = address_params[:zip_code]
      session[:prefecture] = address_params[:prefecture]
      session[:city] = address_params[:city]
      session[:number] = address_params[:number]
      session[:building] = address_params[:building]
      session[:user_id] = @user.id


      @address = Address.new(
        zip_code: session[:zip_code],
        prefecture: session[:prefecture],
        city: session[:city],
        number: session[:number],
        building: session[:building],
        phone_number: session[:phone_number],
        user_id: session[:user_id]
      )

      if @address.save
        #trueの場合@user_idをsessionに格納しdoneへredirect
        #falseの場合residenceにredirect
        session[:id] = @user.id
        #登録したuserでログイン
        sign_in User.find(session[:id]) unless user_signed_in?
        redirect_to new_credit_card_path
      else
        redirect_to residence_signup_index_path
      end

    else
      redirect_to personal_signup_index_path
    end
  end

  def done
    #登録したuserでログイン
    @user = session[:id]
    reset_session
    sign_in User.find(@user) unless user_signed_in?
  end


  private

  def user_params
    params.require(:user).permit(
      :nickname, 
      :email, 
      :password,
      :password_confirmation,
      :family_name,
      :first_name, 
      :family_name_kana, 
      :first_name_kana, 
      :year,
      :month,
      :day,
      :provider,
      :uid
    )
  end

  def address_params
    params.require(:address).permit(
      :zip_code,
      :prefecture,
      :city,
      :number,
      :building,
      :phone_number,
      :user_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/signup/done.html.haml
.single-container
  ​
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg" , alt: "mercari"
  ​
  %main.single-main
    %section.l-single-container
      %h2.l-single-head.registration 会員登録完了
      ​
      .l-single-inner.registration-form
        %center
          ありがとうございます。
          %br/
          会委員登録が完了しました。
        %br/
        %br/
        .l-single-content
          ​
          = link_to root_path, class:"btn-default btn-mail" do
            %i.icon-mail
            メルカリをはじめる
          ​
  = render "footer"

app/views/signup/index.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg", alt: "mercari"
  %main.single-main
    %section.l-single-container
      %h2.l-single-head.registration 新規会員登録
      .l-single-inner.registration-form
        .l-single-content
          = link_to session_clear_signup_index_path ,class:"btn-default btn-mail" do
            %i.icon-mail
            メールアドレスで登録する
          = link_to user_facebook_omniauth_authorize_path, method: :post, id:"facebook-login", class:"btn-default btn-sns btn-sns-facebook" do
            %i.icon-facebook
            Facebookで登録する
          = link_to user_google_oauth2_omniauth_authorize_path, method: :post, id:"google-login",class:"btn-default btn-sns btn-sns-google" do
            Googleで登録する

  = render "footer"

app/views/signup/personal.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg" ,alt: "mercari"
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.active
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
          
  .single-main
    .l-single-container
      .l-single-head.registration 会員情報入力
      .l-single-inner.registration-form
        = form_for @user, url: sms_signup_index_path, method: :get, haml: {class: 'l-single-inner egistration-form'},id:"register-form" do |f|
          .l-single-content
            .form-group
              = f.label :ニックネーム
              %span.form-require 必須
              = f.text_field :nickname, placeholder: '例) メルカリ太郎', value: session[:nickname], class:"input-default"
            .form-group
              = f.label :メールアドレス
              %span.form-require 必須
              = f.email_field :email, placeholder: 'PC・携帯どちらでも可', value: session[:email], class:"input-default"
            .form-group.form-password-revelation
              - if session[:provider] == nil
                = f.label :パスワード
                %span.form-require 必須
                = f.password_field :password, placeholder: '7文字以上の半角英数字', value: session[:password], class:"input-default"
                %p.form-info-text ※ 英字と数字の両方を含めて設定してください
                .form-password-revelation-toggle
                  .checkbox-default
                    %input#reveal_password{type: "checkbox"}/
                    %i.icon-check
                    %label{for: "reveal_password"} パスワードを表示する
                  .form-password-revelation-revealed-password-container
                  %span.form-password-revelation-revealed-password
            .form-group
              %h3.text-left.l-chapter-sub-head 本人確認
              .l-single-text 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .form-group
              = f.label :お名前（全角）
              %span.form-require 必須
              = f.text_field :family_name, placeholder: '例）山田', value: session[:family_name], class:"input-default half"
              = f.text_field :first_name, placeholder: '例）彩', value: session[:first_name], class:"input-default half"
            .form-group
              = f.label :お名前カナ（全角）
              %span.form-require 必須
              = f.text_field :family_name_kana, placeholder: '例）ヤマダ', value: session[:family_name_kana], class:"input-default half"
              = f.text_field :first_name_kana, placeholder: '例）アヤ', value: session[:first_name_kana], class:"input-default half"
            .form-group
              %label{for: "birthday"} 生年月日
              %span.form-require 必須
              %br/
              .birthday-select-wrap
                .select-wrap
                  %i.fas.fa-chevron-down
                  = f.text_field :year, value: session[:year], class:"input-default half"
                %span 年
                .select-wrap.select-wrap__month
                  %i.fas.fa-chevron-down
                  = f.text_field :month, value: session[:month], class:"input-default half"
                %span 月
                .select-wrap.select-wrap__day
                  %i.fas.fa-chevron-down
                  = f.text_field :day, value: session[:day], class:"input-default half"
                %span 日
              %input{name: "birthday", type: "hidden", value: ""}/
              .clearfix
            .form-info-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
            -# .form-group
            -#   私はロボットではありません
            -#   （任意で挿入）
            .form-group
              .l-single-text.text-center
                「次へ進む」のボタンを押すことにより、
                = link_to "利用規約",root_path
                に同意したものとみなします
            .form-group
              = f.submit '次へ進む', class: 'btn-default btn-red'
            .form-group.text-right
              = link_to root_path, target: "_blank" do
                本人情報の登録について
              %i.icon-arrow-right

  = render "footer"

app/views/signup/residence.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg" , alt: "mercari"
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .single-main
    .l-single-container
      .l-chapter-container
        %h2.l-chapter-head 発送元・お届け先住所登録
        = form_for @address, url: signup_create_path , method: :post, html: {class: 'l-single-inner registration-form'} do |f|
          .l-single-content
            .form-group
              = f.label :郵便番号
              %span.form-require 必須
              = f.text_field :zip_code, placeholder: '例) 123-4567', value: session[:zip_code], class:"input-default"
            .form-group
              = f.label :都道府県
              %span.form-require 必須
              = f.select :prefecture, Prefecture.prefecture_areas.keys,{} ,class:"input-default"
            .form-group
              = f.label :市区町村
              %span.form-require 必須
              = f.text_field :city, placeholder: '例)横浜市緑区', value: session[:city], class:"input-default"
            .form-group
              = f.label :番地
              %span.form-require 必須
              = f.text_field :number, placeholder: '例)青山1-1-1', value: session[:number], class:"input-default"
            .form-group
              = f.label :建物名
              %span 任意
              = f.text_field :building, placeholder: '例)柳ビル102', value: session[:building], class:"input-default"
            .form-group
              .form-group
              = f.submit '次へすすむ', class: 'btn-default btn-red'

= render "footer"

app/views/signup/sms.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg", alt: "mercari"
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  .single-main
    .l-single-container
      %h2.l-chapter-head.registration 電話番号の確認
      = form_for @address, url: residence_signup_index_path, method: :get, html: {class: 'l-single-inner registration-form'} do |f|
        .l-single-content
          .form-group
            = f.label :携帯電話の番号
            = f.text_field :phone_number, placeholder: '携帯電話の番号を入力', value: session[:phone_number], class:"input-default"
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
            = f.submit 'SMSを送信する', class: 'btn-default btn-red'
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
            .form-group.text-right
              = link_to  root_path, target: "_blank" do
                電話番号の確認が必要な理由
                %i.icon-arrow-right
          %input{name: "__csrf_value", type: "hidden", value: "acd1491261d2b41a938d75b104dc7631bce87a3fbf722b9b76aa754a0b1c74a2ad0557f31729d4c434dbc68a743e24f48ed8be56d96bd6d1ef89c4150439db755"}/
          %input{name: "id", type: "hidden", value: "740424567"}/

  = render "footer"

app/views/signup/step1.html.haml
.container
  .header
    %h1 mercari (icon挿入)
    .nav
      %ul.nav_contnet
        %li 会員情報
        %li 電話番号認証
        %li お届け先住所入力
        %li 支払い情報
        %li 完了
  .main
    .main-header
      %h2 会員情報入力
    .main-form
      = form_for @user, url: step2_signup_index_path, method: :get, haml: {class: 'first-main__box'} do |f|
        .form-group
          = f.label :ニックネーム
          %span 必須
          = f.text_field :nickname, placeholder: '例) メルカリ太郎'
        .form-group
          = f.label :メールアドレス
          %span 必須
          = f.email_field :email, placeholder: 'PC・携帯どちらでも可'
        .form-group
          = f.label :パスワード
          %span 必須
          = f.password_field :password, placeholder: '7文字以上の半角英数字'
          %p ※ 英字と数字の両方を含めて設定してください
        .form-group
          .text_title
            %h3 本人確認
          .text_display
            %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        .form-group
          = f.label :お名前（全角）
          %span 必須
          = f.text_field :family_name, placeholder: '例）山田'
          = f.text_field :first_name, placeholder: '例）彩'
        .form-group
          = f.label :お名前カナ（全角）
          %span 必須
          = f.text_field :family_name_kana, placeholder: '例）ヤマダ'
          = f.text_field :first_name_kana, placeholder: '例）アヤ'
        .form-group
          = f.label :生年月日
          %span 必須
          .birthday_select
            = f.text_field :year
            %span 年
            = f.text_field :month
            %span 月
            = f.text_field :day
            %span 日
        .form-text
          %p ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        .form-group
          私はロボットではありません
          （任意で挿入）
        .form-group
          %p
            次へ進む」のボタンを押すことにより、
            %a{:href => ""} 利用規約
            に同意したものとみなします
        .form-group
          = f.submit '次へすすむ', class: 'form__submit'

  .footer
    .nav
      %ul.nav_contnet
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引に関する表記
    .footer-logo
      %img{src:""}
      %p © Mercari, Inc.

app/views/signup/step2.html.haml
.container
  .header
    %h1 mercari (icon挿入)
    .nav
      %ul.nav_contnet
        %li 会員情報
        %li 電話番号認証
        %li お届け先住所入力
        %li 支払い情報
        %li 完了
  .main
    .main-header
      %h2 電話番号の確認
    .main-form
      .form-group
        = form_for @address, url: step3_signup_index_path, method: :get, html: {class: 'second-wrapper__box'} do |f|
          = f.label :携帯電話の番号
          = f.text_field :phone_number, placeholder: '携帯電話の番号を入力'
          %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = f.submit 'SMSを送信する', class: 'form__submit'
          %P ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。

  .footer
    .nav
      %ul.nav_contnet
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引に関する表記
    .footer-logo
      %img{src:""}
      %p © Mercari, Inc.

app/views/signup/step3.html.haml
.container
  .header
    %h1 mercari (icon挿入)
    .nav
      %ul.nav_contnet
        %li 会員情報
        %li 電話番号認証
        %li お届け先住所入力
        %li 支払い情報
        %li 完了
  .main
    .main-header
      %h2 発送元・お届け先住所登録
    .main-form
      = form_for @address, url: signup_index_path, method: :post, html: {class: 'forth-main-wrapper__box'} do |f|
        .form-group
          = f.label :郵便番号
          %span 必須
          = f.text_field :zip_code, placeholder: '例) 123-4567'
        .form-group
          = f.label :都道府県
          %span 必須
          = f.text_field :prefectur, placeholder: '現状テキスト型'
        .form-group
          = f.label :市区町村
          %span 必須
          = f.text_field :city, placeholder: '例)横浜市緑区'
        .form-group
          = f.label :番地
          %span 必須
          = f.text_field :number, placeholder: '例)青山1-1-1'
        .form-group
          = f.label :建物名
          %span 任意
          = f.text_field :building, placeholder: '例)柳ビル102'
        .form-group
          = f.label :電話
          %span 任意
          = f.text_field :phone_number, placeholder: '例)09011111111'
        .form-group
          .form-group
          = f.submit '次へすすむ', class: 'form__submit'

  .footer
    .nav
      %ul.nav_contnet
        %li プライバシーポリシー
        %li メルカリ利用規約
        %li 特定商取引に関する表記
    .footer-logo
      %img{src:""}
      %p © Mercari, Inc.