config/routes.rb
Rails.application.routes.draw do

  #omniauth_callbacksコントローラーを定義することで、各SNSからの認証リクエストに対するコールバック関数を受け取れる(Rails routesで確認可)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    #サインアウトを別箇で用意しないとログアウト処理ができない為記述
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #トップページ
  root to: 'homes#index'

  #カテゴリ一覧用のルーティング記述(現時点では不使用)
  resources :brands_category, only: [:index, :show] 
  resources :category, only: [:index, :show] 

  #新規登録関連のルーティング記述
  resources :signup do
    collection do
      get "session_clear"
      get 'personal'
      get 'sms'
      get 'residence'
      get "done"
    end
  end
  post "signup/create" => "signup#create" #URIを取得する為作成
  
  #クレジット登録関連のルーティング記述
  resources :credit_card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_card#pay'
      post 'destroy', to: 'credit_card#destroy'
    end
  end


  #itemのshowアクションで商品詳細
  resources :items do
    collection do
      get 'search' => 'items#search' #検索
      delete :imgdestroy, path: '/image/:id' #編集での画像削除用アクション
    end
  end

  #マイページ
  resources :mypages, only: [:show] do
    collection do
      # get 'edit', to: 'mypages#edit'#プロフィール編集用      意味不明につき残すだけ残します
      # patch 'edit', to: 'mypages#update'#プロフィール更新用      
      get 'credit' # カード情報登録
      get 'logout' #ログアウト用ページ
      get 'identification' #本人情報
      get 'profile' #プロフィール情報
    end
    member do
      get 'list'#出品リスト
    end
  end  

  #購入
  resources :transaction, only: [:index, :show] do
    collection do 
      get 'done', to: 'transaction#done'#購入完了
    end
    member do
      post 'pay', to: 'transaction#pay'#購入、支払い
      patch 'pay', to: 'transaction#pay' #更新
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  # validates :zip_code, :prefecture, :city, :number, :user_id, presence: :true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brands_category.rb
class BrandsCategory < ApplicationRecord
  has_many :items
end

app/models/category.rb
class Category < ApplicationRecord
  # 現時点では使用していないためコメントアウト化
  # has_ancestry
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :brands_category
  belongs_to :size, optional: true
  belongs_to :item_condition
  
end

app/models/item_condition.rb
class ItemCondition < ApplicationRecord
  has_many :items
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  enum prefecture_area:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :item, optional: true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :credit_cards, dependent: :destroy

  validates :nickname, :email, :encrypted_password, :family_name, :first_name, :family_name_kana, :first_name_kana, :year, :month, :day, presence: :true
  validates :family_name_kana, :first_name_kana, presence: :true, if: :name_kana?

  #各SNSより取得したprovider情報をauthに代入し、Userテーブル内に該当するレコードがあればuserに代入
    def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    #userがなければ新規インスタンスをハッシュ形式で作成
    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        nickname: auth.info.name,
      )
    end
    #userを本メソッドの返り値とする
    user
  end

  #カナカナ入力のバリデーション
  def name_kana?
    input_type = /^([ァ-ン]|ー)+$/
  end

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController

  before_action :set_item, only: [:show, :pay]
  before_action :set_card, only: [:show, :pay]

  def show
    #テーブルからpayjpの顧客IDを検索
    if @card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_credit_card_path
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    if @card
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      Payjp::Charge.create(
        amount: @item.price, #itemテーブルの価格情報を取得
        customer: @card.customer_id, #顧客ID
        currency:'jpy', #日本円
      )
      @item.update(item_params)
      redirect_to done_transaction_index_path #完了画面に移動
    else
      redirect_to root_path
    end
  end

  def done
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_card
    @card = CreditCard.where(user_id: current_user.id).first
  end

  def item_params
    params.require(:item).permit!
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transaction/_footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー", root_path
      %li
        = link_to "メルカリ利用規約", root_path
      %li
        = link_to "特定商取引に関する表記", root_path
  = link_to root_path ,class:"single-footer-logo" do
    = image_tag "logo-gray.svg", alt: "mercari", height: "65", width: "80"
  %p
    -# %small © Mercari, Inc.

app/views/transaction/done.html.haml
-# //商品購入完了ページ（仮）
-# %h1 購入が完了しました！
-# = link_to root_path do
-#   %h2 トップページへ

.single-container
  ​
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg" , alt: "mercari"
  ​
  %main.single-main
    %section.l-single-container
      %h2.l-single-head.registration 購入完了
      ​
      .l-single-inner.registration-form
        %center
          ありがとうございます。
          %br/
          購入が完了しました！
        %br/
        %br/
        .l-single-content
          ​
          = link_to root_path, class:"btn-default btn-mail" do
            %i.icon-mail
            トップページへ
          ​
  = render "footer"

app/views/transaction/show.html.haml
//購入する商品の確認画面
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg", alt: "mercari" 
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-chapter-head 購入内容の確認
      %section.buy-content.buy-item
        .buy-content-inner
          .buy-item-box
            %h3.buy-item-image
              .lazyloaded
                = image_tag ""
            .buy-item-detail
              %p.buy-item-name= @item.name
              %p.buy-price-ja.bold
                %span= @item.price
                %span.item-shipping-fee （税込）送料込み
                
      %section.buy-content.buy-item
        .buy-content-inner
          .buy-form
            %ul.buy-price-table
              %li.buy-price-row.buy-you-pay.bold
                .buy-price-cell.buy-price-cell-label 支払い金額
                .buy-price-cell
            %ul.buy-accordion.buy-not-have-point
              %li.accordion-parent
                .checkbox-default.buy-use-point
                  %i.icon-check
                  %label ポイントを使用 (所持ポイント: P0)
            %section.buy-content.buy-user-info
              .buy-content-inner
                .clearfix
                  %h3.l-left 支払い方法
                  .l-right.buy-user-info-fix
                    %span 変更する
                %p.buy-user-info-text
                  - if @default_card_information.blank?
                  - else
                    -#以下カード情報を表示
                    = "**** **** **** " + @default_card_information.last4
                    有効期限
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
                    %figure.buy-card-logo
                      = image_tag "visa.svg", height: "15", width: "49"
                    %section.buy-content.buy-user-info
                      .buy-content-inner
                        .clearfix
                          %h3.l-left 配送先
                          %l-right.buy-user-info-fix
                            %span 変更する
                        %address.buy-user-info-text
                          %p
                            = current_user.address.zip_code
                            %br/
                            = current_user.address.prefecture
                            = current_user.address.city
                            = current_user.address.number
                            %br/
                            = current_user.nickname
                    %section.buy-content.buy-user-info
                      = form_with model: @item, local: true, url: pay_transaction_path(@item), method: :patch do |form|
                        = form.hidden_field :shopping_status, value: 1
                        %button.btn-default.btn-red.bold
                          = form.submit value:'購入する'
                      
  %footer.single-footer
    %nav
      %ul.clearfix
        %li
          = link_to "" do
            プライバシーポリシー
        %li
          = link_to "" do
            メルカリ利用規約
        %li
          = link_to "" do
            特定商取引に関する表記
    = link_to "" do
      .single-footer-logo
        = image_tag "logo-gray.svg", alt: "mercari", height: "65", width: "80"
    %p
      -# %small © Mercari, Inc.