config/routes.rb
Rails.application.routes.draw do

  #omniauth_callbacksコントローラーを定義することで、各SNSからの認証リクエストに対するコールバック関数を受け取れる(Rails routesで確認可)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    #サインアウトを別箇で用意しないとログアウト処理ができない為記述
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #トップページ
  root to: 'homes#index'

  #カテゴリ一覧用のルーティング記述(現時点では不使用)
  resources :brands_category, only: [:index, :show] 
  resources :category, only: [:index, :show] 

  #新規登録関連のルーティング記述
  resources :signup do
    collection do
      get "session_clear"
      get 'personal'
      get 'sms'
      get 'residence'
      get "done"
    end
  end
  post "signup/create" => "signup#create" #URIを取得する為作成
  
  #クレジット登録関連のルーティング記述
  resources :credit_card, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credit_card#pay'
      post 'destroy', to: 'credit_card#destroy'
    end
  end


  #itemのshowアクションで商品詳細
  resources :items do
    collection do
      get 'search' => 'items#search' #検索
      delete :imgdestroy, path: '/image/:id' #編集での画像削除用アクション
    end
  end

  #マイページ
  resources :mypages, only: [:show] do
    collection do
      # get 'edit', to: 'mypages#edit'#プロフィール編集用      意味不明につき残すだけ残します
      # patch 'edit', to: 'mypages#update'#プロフィール更新用      
      get 'credit' # カード情報登録
      get 'logout' #ログアウト用ページ
      get 'identification' #本人情報
      get 'profile' #プロフィール情報
    end
    member do
      get 'list'#出品リスト
    end
  end  

  #購入
  resources :transaction, only: [:index, :show] do
    collection do 
      get 'done', to: 'transaction#done'#購入完了
    end
    member do
      post 'pay', to: 'transaction#pay'#購入、支払い
      patch 'pay', to: 'transaction#pay' #更新
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  # validates :zip_code, :prefecture, :city, :number, :user_id, presence: :true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brands_category.rb
class BrandsCategory < ApplicationRecord
  has_many :items
end

app/models/category.rb
class Category < ApplicationRecord
  # 現時点では使用していないためコメントアウト化
  # has_ancestry
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :brands_category
  belongs_to :size, optional: true
  belongs_to :item_condition
  
end

app/models/item_condition.rb
class ItemCondition < ApplicationRecord
  has_many :items
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  enum prefecture_area:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :item, optional: true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :credit_cards, dependent: :destroy

  validates :nickname, :email, :encrypted_password, :family_name, :first_name, :family_name_kana, :first_name_kana, :year, :month, :day, presence: :true
  validates :family_name_kana, :first_name_kana, presence: :true, if: :name_kana?

  #各SNSより取得したprovider情報をauthに代入し、Userテーブル内に該当するレコードがあればuserに代入
    def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    #userがなければ新規インスタンスをハッシュ形式で作成
    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        nickname: auth.info.name,
      )
    end
    #userを本メソッドの返り値とする
    user
  end

  #カナカナ入力のバリデーション
  def name_kana?
    input_type = /^([ァ-ン]|ー)+$/
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    #category_idの値は実際のメルカリ準拠。投稿時間を降順で最大10個表示させる。
    @ladys_items   = Item.where(category_id: 1).order("created_at DESC").limit(10)
    @mans_items    = Item.where(category_id: 2).order("created_at DESC").limit(10)
    @kaden_items   = Item.where(category_id: 8).order("created_at DESC").limit(10)
    @toy_items     = Item.where(category_id: 6).order("created_at DESC").limit(10)


  #例として、下記記述で各アイテムのタイトル、値段、画像(1枚目のみ)を取得することが可能(classは省略)
  #今後ビューファイルに反映させる際の参考コードとして下記記述を残す。
  # %h2 レディース新着アイテム
  # - @ladys_items.each do |lady|
  #   = lady.item
  #   = lady.price
  #   %img{src: "#{lady.images.first.image}", width:"300", height:"300"}
  end
  
  def new
   @item = Item.new
   @item.images.build
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      # 配列の10個目までの画像を保存
      params[:images][:image].first(10).each do |image|
        @item.images.create(image: image)
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @address = Address.find_by(user_id: @item.user_id)
  end

  def destroy
    if @item.destroy
      redirect_to mypage_path(current_user)
    else
      redirect_to edit_item_path(params[:id])
    end
  end

  def imgdestroy
    # 編集画面の画像削除専用アクション
    image = Image.find(params[:id])
    image.destroy
  end

  def edit
  end

  def update
    if @item.update(update_params)
      # paramsにimagesのキーが有るかで分岐(新規の画像があればtrue、なければfalse)
      if params.has_key?(:images) 
        params[:images][:image].each do |image|
        @item.images.create(image: image)
        # 商品の画像が合計10枚に達したらeach do処理を止める
        if @item.images.length == 10 then
          break
        end
        end
      end
      redirect_to item_path	
    else	
      render :edit 	
    end
  end

  def search
    # like句によるあいまい検索
    @items = Item.where('item LIKE(?)', "%#{params[:keyword]}%").order("id DESC")
    if params[:keyword] == ""
      redirect_to '/items/search?utf8=✓&keyword=+++'
    end
    if @items.count == 0
      @all_items = Item.limit(5).order("id DESC")
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :price,
      :category_id,
      :brands_category_id,
      :shopping_status,
      :size_id,
      :item_condition_id,
      :delivery_charge,
      :date,
      image_attributes: [:image, :id]
      ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def update_params	
    params.require(:item).permit(	
      :name,	
      :description,	
      :price,	
      :category_id,	
      :brands_category_id,	
      :shopping_status,	
      :size_id,	
      :item_condition_id,	
      :delivery_charge,
      :date,      
      image_attributes: [:image, :id]	
      )	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credit_card_helper.rb
module CreditCardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_footer.html.haml
%aside.app-banner
  .app-banner-pc
    .app-banner-pc-inner
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner-icon.clearfix
        %figure
          = image_tag "mercari_icon copy.png", alt: "", width: "68"
        %ul.clearfix
          %li
            = link_to "https://apps.apple.com/jp/app/id667861049?l=ja", target: "_blank" do
              = image_tag "app-store.svg", alt: "mercari", height: "40", width: "133"
          %li
            = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target: "_blank" do
              = image_tag "google-play.svg", alt: "mercari", height: "40", width: "133"
    %figure
      = image_tag "download_content_pc.png", alt: ""
%footer.global-footer
  %nav.clearfix
    .footer-cell
      %h2.footer-head メルカリについて
      %ul
        %li
          = link_to "会社概要（運営会社）", root_path
        %li
          = link_to "採用情報", root_path
        %li
          = link_to "プレスリリース", root_path
        %li
          = link_to"公式ブログ", root_path
        %li
          = link_to "メルカリロゴ利用ガイドライン", root_path
        %li.footer-social-link
          = link_to root_path, target: "_blank" do
            %i.icon-twitter
        %li.footer-social-link
          = link_to root_path, target: "_blank" do
            %i.icon-facebook
    .footer-cell
      %h2.footer-head ヘルプ＆ガイド
      %ul
        %li
          = link_to "メルカリガイド", root_path
        %li
          = link_to "らくらくメルカリ便", root_path
        %li
          = link_to "ゆうゆうメルカリ便", root_path
        %li
          = link_to "大型メルカリ便", root_path
        %li
          = link_to "車体取引ガイド", root_path
        %li
          = link_to "メルカリあんしん・あんぜん宣言！", root_path
        %li
          = link_to "偽ブランド品撲滅への取り組み", root_path
        %li
          = link_to "メルカリボックス", root_path
    .footer-cell.full-width
      %h2.footer-head プライバシーと利用規約
      .inner-footer-cell
        %ul
          %li
            = link_to "プライバシーポリシー", root_path
          %li
            = link_to "メルカリ利用規約", root_path
          %li
            = link_to "あんしんスマホサポート制度に関する利用特約", root_path
          %li
            = link_to "コンプライアンスポリシー", root_path
      .inner-footer-cell
        %ul
          %li
            = link_to "個人データの安全管理に係る基本方針", root_path
          %li
            = link_to "特定商取引に関する表記", root_path
          %li
            = link_to "資金決済法に基づく表示",root_path
          %li
            = link_to "法令順守と犯罪抑止のために", root_path
    .footer-cell.footer-nav-lang
      %h2.footer-head 国
      %ul
        %li
          = link_to "日本", root_path
        %li
          = link_to "United States", root_path
          
  .footer-bottom
    = link_to root_path do
      = image_tag "logo-white.svg", alt: "mercari", height: "31", width: "124"
    %span.footer-copyright
      -# %small © Mercari, Inc.

//出品ボタン    
- if user_signed_in?  
  = link_to new_item_path ,class: "footer-sell-btn" do
    %div 出品
    %i.fas.fa-camera
- else
  = link_to  new_user_session_path ,class: "footer-sell-btn" do
    %div 出品
    %i.fas.fa-camera
    

app/views/items/edit.html.haml
.single-container
  %header.single-header
    %h1
      = link_to root_path do
        = image_tag "logo-1.svg", alt: "mercari"
  %main.single-main
    %section.l-single-container.buy-item-container
      #sell-container
        .sell-container-inner
          %h2.l-single-head 商品の情報を入力
          = form_with(model: @item , method: :patch, local: true) do |f|
            .sell-upload-box
              %h3.sell-upload-head
                出品画像
                %span.form-require 必須
              %p 最大10枚までアップロードできます
              .sell-dropbox-container.clearfix.state-image-number-10
                - @item.images.each do |img|
                  .preview-box
                    .preview-box__img-box
                      = image_tag "#{img.image}", height:"118", width:"118", class:"image"
                    .preview-box__select-2
                      = link_to imgdestroy_items_path(img.id), method: :delete do
                        %p 削除
                .sell-upload-items-container
                  .sell-upload-items.have-item-0
                %label.sell-upload-drop-box.have-item-0
                  = f.fields_for :images do |image|
                    = image.file_field :image, multiple: true, name: "images[image][]", class:"boxfileselect fileup_last"
                  %pre.visible-pc
                    クリックしてファイルをアップロード
            .sell-content
              .form-group
                %label
                  商品名
                  %span.form-require 必須
                = f.text_field :name, placeholder: "商品名", class:"input-default"
              .form-group
                %label
                  商品の説明
                  %span.form-require 必須
                = f.text_area :description, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5", class:"textarea-default"
            .sell-content.clearfix
              %h3.sell-sub-head 商品の詳細
              .sell-form-box
                .form-group
                  %label
                    カテゴリー
                    %span.form-require 必須
                    .select-wrap
                      %i.fas.fa-chevron-right.a
                      = f.select :category_id,[["レディース","1"],["メンズ","2"],["ベビー・キッズ","3"],["インテリア・住まい・小物","4"],["本・音楽・ゲーム","5"],["おもちゃ・ホビー・グッズ","6"],["コスメ・香水・美容","7"],["家電・スマホ・カメラ","8"],["スポーツ・レジャー","9"],["ハンドメイド","10"],["チケット","11"],["自動車・オートバイ","12"],["その他","13"]], {}, {class: 'select-default'}
                .form-group
                  %label
                    ブランド
                    .select-wrap
                      %i.fas.fa-chevron-right.a
                      = f.select :brands_category_id,[["---","1"],["シャネル","2"],["ナイキ","3"],["ルイ・ヴィトン","4"], ["シュプリーム","5"],["アディダス","6"]],{}, {class:"select-default"}                      
                .form-group
                  %label
                    サイズ
                    .select-wrap
                      = f.select :size_id,[["---","1"],["S","2"],["M","3"],["L","4"], ["XL","5"],["20.0","6"],["20.5","7"],["21.0","8"],["21.5","9"],["22.0","10"],["22.5","11"],["23.0","12"],["23.5","13"],["24.0","14"],["24.5","15"],["25.0","16"],["25.5","17"],["26.0","18"],["26.5","19"],["27,0","20"],["27.5","21"],["28.0","22"],["28.5","23"],["29.0","24"],["29.5","25"],["30.0","26"]],{}, {class:"select-default"}                
                .form-group
                  %label
                    商品の状態
                    %span.form-require 必須
                    .select-wrap
                      %i.fas.fa-chevron-right.b
                      = f.select :item_condition_id, [["新品、未使用","1"],["未使用に近い","2"],["目立った傷や汚れなし","3"],["やや傷や汚れあり","4"],["傷や汚れあり","5"],["全体的に状態が悪い","6"]],{}, {class:"select-default"}
            .sell-content.clearfix
              %h3.sell-sub-head 配送について
              .sell-form-box
                .form-group
                  %label
                    配送料の負担
                    %span.form-require 必須
                  .select-wrap
                    %i.fas.fa-chevron-right.a
                    = f.select :delivery_charge,[["送料込み(出品者負担)"],["着払い(購入者負担)"]],{}, {class:"select-default"}
                .form-group
                  %label
                    発送までの日数
                    %span.form-require 必須
                  .select-wrap
                    %i.fas.fa-chevron-right.a
                    = f.select :date,[["1~2日で発送"],["2~3日で発送"],["4~7日で発送"]],{}, {class:"select-default"}
            .sell-content.clearfix
              %h3.sell-sub-head 販売価格(300〜9,999,999)

              .sell-form-box
                %ul.sell-price
                  %li.form-group
                    .clearfix
                      %label.l-left
                        価格
                        %span.form-require 必須
                      .l-right.sell-price-input
                        = f.text_field :price, placeholder: "例) 300",class:"input-default", id:"price_calc"
                  %li.clearfix
                    .l-left
                      販売手数料 (10%)
                    .l-right1 -
                  %li.clearfix.bold
                    .l-left 販売利益
                    .l-right2 -
            .modal{role: "dialog", tabindex: "-1"}
              .modal-inner
            .sell-content.sell-btn-box
              = f.submit '変更する', class: 'btn-red btn-default'
              = link_to "もどる", root_path, class:"btn-default btn-gray"
          .overlay

= render "footer"

app/views/items/search.html.haml
1

app/views/items/show.html.haml
.default-container
  %header.pc-header.visible-pc
    .pc-header-inner
      .pc-header-top
        %h1
          = link_to root_path do
            = image_tag "logo-1.svg", alt: "mercari", height: "36", width: "134"
        %form.pc-header-form{action: "https://www.mercari.com/jp/search/"}
          %input.input-default{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}/
          %i.fas.fa-search{action: "https://www.mercari.com/jp/search/"}
      .pc-header-nav-box.clearfix
        %nav.l-left
          %ul.pc-header-nav
            %li
              %h2
                = link_to "" do
                  .pc-header-nav-root.list-parent
                    %i.fas.fa-align-justify
                    %span カテゴリーから探す
              %ul.pc-header-nav-parent-wrap{"data-mega": "1"}
                %li.pc-header-nav-parent
            %li
              %h2
                = link_to "" do
                  .pc-header-nav-root.list-parent
                    %i.fas.fa-external-link-alt 
                    %span ブランドから探す
                %ul.pc-header-nav-parent-wrap
                  %li.pc-header-nav-parent
                    %h3  
      
  %main.l-container.clearfix
    %section.item-box-container.l-single-container
      .item-name 
        = @item.name
      .item-main-content.clearfix
        .item-photo
          = image_tag "#{@item.images.first.image}"
          - @item.images.each do |image|
            = image_tag "#{image.image}", width: "60", height: "60"
          - if @item.shopping_status == 1
            .items-box_photo__sold2
              .items-box_photo__sold2__inner2
                SOLD
        %table.item-detail-table
          %tbody
            %tr
              %th 出品者
              %td
                = link_to "" do
                  = @item.user.nickname
                %div
                  .item-user-ratings
                    %i.icon-good
                    %span 2
                  .item-user-ratings
                    %i.icon-normal
                    %span 0
                  .item-user-ratings
                    %i.icon-bad
                    %span 0
            %tr
              %th カテゴリー
              %td
                = @item.category.name
            %tr
              %th ブランド
              %td
                = link_to "" do
                  = @item.brands_category.name
            %tr
              %th 商品のサイズ
              %td 
                = @item.size.name
            %tr
              %th 商品の状態
              %td 
                = @item.item_condition.name
            %tr
              %th 配送料の負担
              %td 
                = @item.delivery_charge
            %tr
              %th 配送の方法
              %td らくらくメルカリ便
            %tr
              %th 配送元地域
              %td
                = @address.prefecture
            %tr
              %th 発送日の目安
              %td
                = @item.date
      .item-price-box.text-center
        %span.item-price.bold 
          ¥
          = @item.price
        %span.item-tax (税込)
        %span.item-shipping-fee 送料込み

        //商品の出品者の画面
      -if user_signed_in? && @item.user_id == current_user.id
        .listing-item-change-box
          = link_to edit_item_path(@item) do
            .btn-default.btn-red 商品の編集
          .text-center or
          = link_to item_path(@item), method: :delete, data: {confirm: "削除してもよろしいですか？"} do
            .btn-default.btn-gray この商品を削除する
      -else 
        //商品購入者の画面
        //リンク先仮指定（後ほど変更）
        - if @item.shopping_status == 1
          = link_to root_path do
            .item-buy-btn この商品は売り切れました
        -else
          = link_to transaction_path(@item) do
            .item-buy-btn 購入画面に進む

        %a.item-action-text{"data-action": "item/openDetail", "data-adjust-url": "http://app.adjust.io/xio2ii?campaign=iOS&adgroup=items.buy_button1", "data-key": "id=m82477556805", "data-play-id": "com.kouzoh.mercari", "data-toggle": "open-app", "data-url-scheme": "mercari://"}
          アプリで購入

        //下記、全ての出品物によって記載が違うので割愛(参考に残しておく)
      -# .item-description.f14
      -#   %p.item-description-inner
      -#     【ブランド】
      -#     = @item.brands_category.name
      -#     -# 【  カラー 】カーキ
      -#     -# 【 サイズ  】レディース S
      -#     -# 【購入時期】2018年
      -#     -# 【着用回数】2、3回 (着用時間も合わせて数時間程度)
      -#     -# 【保管状況】自宅保管
          
      -#     -# ラインがきれいでスッキリ見えます。
      -#     -# 同時時期に購入したロング丈しか着ないため出品します。
          
      -#     -# ※あくまでもユーズドであることをご理解ただける方のみのご購入でお願いいたします。
      
    .item-detail-message
      .message-container
        .message-content
          %form.message-form{action: "https://www.mercari.com/jp/comment/add/", method: "POST"}
            %input{name: "__csrf_value", type: "hidden", value: "bd7d063ce94f634e6ac4abaf496a8f4fd079cdb874c2ce2f4fe92d4d899e524691e2ab04f8ffe7634c5cd619a2975b2c40f822f5077dd7f648b30cf8c58cd9f3e"}/
            相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %input{name: "item_id", type: "hidden", value: "m82477556805"}/
            %input{name: "redirect_url_key", type: "hidden", value: "item_detail"}/
            %textarea.textarea-default{name: "body", type: "text", value: ""}
            %button.message-submit.btn-default.btn-gray{type: "submit"}
              %span コメントする
        %aside.modal{"data-close": "modal", "data-modal": "delete-comment"}
          .modal-inner.modal-banner
            .modal-body
              .modal-head.bold 確認
              %div{"data-comment": "body"}
              %br/
              本当にこのコメントを削除してよろしいですか？
            %form{action: "https://www.mercari.com/jp/comment/delete/", method: "POST"}
              .clearfix
                .modal-btn.modal-btn-cancel{"data-close": "modal"} キャンセル
                %button.modal-btn.modal-btn-submit{type: "submit"}
                  削除する
              %input{name: "item_id", type: "hidden", value: "m82477556805"}/
              %input{name: "comment_id", type: "hidden", value: ""}/
              %input{name: "redirect_url_key", type: "hidden", value: "item_detail"}/
              %input{name: "__csrf_value", type: "hidden", value: "bd7d063ce94f634e6ac4abaf496a8f4fd079cdb874c2ce2f4fe92d4d899e524691e2ab04f8ffe7634c5cd619a2975b2c40f822f5077dd7f648b30cf8c58cd9f3e"}/

= render "footer"